# --- Prometheus --------------------------------------------------------
- name: Prometheus | Install the Prometheus server
  apt:
    name: prometheus

- name: Prometheus | Configure the Prometheus server
  copy:
    src: monitoring/prometheus.yml
    dest: /etc/prometheus/prometheus.yml

- name: Prometheus | Ensure Prometheus is started and starts at host boot
  service:
    name: prometheus
    enabled: true
    state: started

- name: Prometheus | Check if Prometheus is accessible
  uri:
    url: http://localhost:9090/graph
    method: GET
    status_code: 200

# --- Grafana -----------------------------------------------------------
- name: Grafana | Import Grafana GPG signing key
  apt_key:
    url: "https://packages.grafana.com/gpg.key"
    state: present
    validate_certs: false
  register: _add_apt_key
  until: _add_apt_key is succeeded
  retries: 5
  delay: 2

- name: Grafana | Add Grafana repository
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: true
  register: _update_apt_cache
  until: _update_apt_cache is succeeded
  retries: 5
  delay: 2
  when:
    - ansible_pkg_mgr == "apt"

- name: Grafana | Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: yes

- name: Grafana | Copy Grafana configuration file
  copy:
    src: monitoring/grafana.ini
    dest: /etc/grafana/grafana.ini

- name: Grafana | Ensure Grafana is started and starts at host boot
  service:
    name: grafana-server
    enabled: true
    state: started

- name: Grafana | Add Prometheus as datasource to Grafana
  grafana_datasource:
    name: Prometheus
    grafana_url: http://localhost:3000
    grafana_user: admin
    grafana_password: admin
    ds_type: prometheus
    is_default: yes
    url: http://127.0.0.1:9090
    state: present

# https://grafana.com/grafana/dashboards/1860
- name: Grafana | Import Grafana dashboard Node Exporter Full
  grafana_dashboard:
    grafana_url: http://localhost:3000
    grafana_user: admin
    grafana_password: admin
    state: present
    message: Updated by ansible
    overwrite: yes
    path: monitoring/node-exporter-full.json

- name: Grafana | Restart the Prometheus service
  service:
    name: prometheus
    state: restarted

- name: Grafana | Restart the Grafana service
  service:
    name: grafana-server
    state: restarted
