---
# tasks file for nginx & pm2

- name: Nginx & PM2 | Install Nginx
  apt:
    name: nginx
    state: present

- name: Nginx & PM2 | Start Nginx
  service:
     name: nginx
     state: present
     update_cache: yes
     notify: restart nginx

- name: Nginx & PM2 | Install PM2
  npm:
    name: pm2
    global: yes
