---
# tasks file for nginx & pm2

- name: Nginx & PM2 | Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Nginx & PM2 | Start Nginx
  service:
    name: nginx
    state: started

- name: Nginx & PM2 | Install PM2
  npm:
    name: pm2
    global: yes
