---
- hosts: development
  become: true
  become_method: sudo

  tasks:
    - name: Check for /var/www/apps directory
      stat:
        path: /var/www/apps
      register: apps_dir

    - name: Create directory if not exists
      file:
        path: /var/www/apps
        state: directory
        mode: 755
      when: apps_dir.stat.exists == false

    - name: Copy files to development host
      copy:
        src: /var/lib/jenkins/jobs/Development/workspace/app/crud-app.zip
        dest: /var/www/apps
        mode: 755

    - name: Unzip app on development host
      unarchive:
        src:  /var/www/apps/crud-app.zip
        dest: /var/www/apps
        remote_src: yes
        mode: 755

# cdn

# pm2 starten....
