---
- hosts: development
  become: true

  tasks:
    - name: Check for /var/www directory
      stat:
        path: /var/www
      register: var_www

    - name: Create directory if not exists
      file:
        path: /var/www
        state: directory
        mode: 755
      when: var_www.stat.exists == false

    - name: Copy files to remote host
      copy:
        src: dist/
        dest: /var/www/
        mode: 755
