---
- hosts: development
  become: true
  become_method: sudo

  tasks:
    - name: Check for /var/www directory
      stat:
        path: /var/www
      register: www_dir

    - name: Create directory if not exists
      file:
        path: /var/www
        state: directory
        mode: 755
      when: www_dir.stat.exists == false

    - name: Check for /var/www/apps directory
      stat:
        path: /var/www/apps
      register: apps_dir

    - name: Create directory if not exists
      file:
        path: /var/www/apps
        state: directory
        mode: 755
      when: apps_dir.stat.exists == false

    - name: Copy crud-app.zip to development host
      copy:
        src: /var/lib/jenkins/jobs/Development/workspace/app/crud-app.zip
        dest: /var/www/apps
        mode: 755

#    - name: Remove crud-app directory if exists
#      command: rm -R -f dist || echo no crud-app dist directory
#      args:
#        chdir:  /var/www/apps

#    - name: Unzip crud-app on development host and create crud-app directory
#      unarchive:
#        src:  /var/www/apps/crud-app.zip
#        dest: /var/www/apps
#        remote_src: yes
#        mode: 755

#    - name: Start app with PM2
#      command: pm2 start npm -- start
#      args:
#        chdir:  /var/www/apps/dist
