---
- name: Deploy application to production environment
  hosts: production

  vars:
    server_name: hero-app.de
    root_dir: /var/www/apps/dist

  tasks:
    - name: Check for /var/www/apps directory
      stat:
        path: /var/www/apps
      register: apps_dir

    - name: Create /var/www/apps directory if not exists
      file:
        path: /var/www/apps
        state: directory
        mode: 755
      when: apps_dir.stat.exists == false
      become: yes

    - name: Copy crud-app.zip to production host
      copy:
        src: /var/lib/jenkins/jobs/Production/workspace/app/crud-app.zip
        dest: /var/www/apps
        mode: 755
      become: yes

    - name: Remove crud-app dist directory if exists
      file:
        path: /var/www/apps/dist
        state: absent
      become: yes

    - name: Unzip crud-app
      unarchive:
        src:  /var/www/apps/crud-app.zip
        dest: /var/www/apps
        remote_src: yes
      become: yes

    - name: Add config template to nginx available sites
      template:
        src: nginx.conf
        dest: "/etc/nginx/sites-available/{{ server_name }}.conf"
      become: yes

    - name: Enable config template from nginx available sites
      file:
        src: "/etc/nginx/sites-available/{{ server_name }}.conf"
        dest: "/etc/nginx/sites-enabled/{{ server_name }}.conf"
        state: link
      become: yes

    - name: Add enabled nginx site to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: "{{ server_name }}"
        line: "127.0.0.1 {{ server_name }}"
      become: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

    - name: Copy server.zip dir to production host
      copy:
        src: /var/lib/jenkins/jobs/Production/workspace/app/server.zip
        dest: /var/www/apps
        mode: 755
      become: yes

    - name: Remove crud-app server directory if exists
      file:
        path: /var/www/apps/server
        state: absent
      become: yes

    - name: Unzip crud-app server
      unarchive:
        src:  /var/www/apps/server.zip
        dest: /var/www/apps
        remote_src: yes
      become: yes

    - name: Install server packages based on package.json
      npm:
        path: /var/www/apps/server
      become: yes

    - name: Delete old PM2 server process if present
      command: pm2 stop server.js
      args:
        chdir:  /var/www/apps/server
      ignore_errors: yes
      become: yes

    - name: Start server with PM2
      command:  pm2 start server.js
      args:
        chdir:  /var/www/apps/server
      become: yes
