---
# file for installing node, mongodb, nginx, pm2 & sshpass on development environment

- hosts: development
  remote_user: ansible
  become: yes
  become_method: sudo

  vars:
    #variable needed during node installation
    temp_folder: /tmp

  tasks:
    # Install Prerequisites
    - include: tasks/prerequisites.yml

    # Install MongoDB
    - include: tasks/mongodb.yml

    # Install NodeJS
    - include: tasks/nodejs.yml

    # Install Nginx & PM2
    - include: tasks/nginx.yml

