---
# file for installing jenkins on jenkins vm

- name: Install Jenkins Role and create pipeline
  hosts: jenkins
  become: yes
  become_method: sudo

  tasks:
    # Install prerequisites
    - include: tasks/prerequisites.yml

  roles:
  - role: roles/java
  - role: roles/jenkins
