---
# file for installing jenkins on jenkins vm

- name: Install Jenkins Role and create pipeline
  hosts: jenkins
  become: yes
  become_method: sudo

  tasks:
    # Install Node.js
    - include: tasks/nodejs.yml

  roles:
  - role: geerlingguy.java
    become: yes
  - role: roles/jenkins
