---
# file for installing jenkins on jenkins vm

- name: Install Jenkins Role and create pipeline
  hosts: all

  roles:
  - role: roles/ansible-role-java
    become: yes
  - role: roles/ansible-role-jenkins
    become: yes
