# The full config is at:
#   https://prometheus.io/docs/operating/configuration/

global:
  # How frequently to scrape targets by default.
  scrape_interval: 15s

scrape_configs:

  - job_name: 'development'
    static_configs:
      - targets: ['192.168.33.27:9100']

  - job_name: 'production'
    static_configs:
      - targets: ['192.168.33.28:9100']

  - job_name: 'jenkinsMonitoring'
    static_configs:
      - targets: ['localhost:9100']
